### ISSUE TITLE
[Bug] Horizontal scroll appearing on official installation  docs  page of Vocabulary

### ISSUE THREAD

**Issue by OmarAmeen01** [creativecommons/vocabulary#80] opened 2024-10-04 09:39 UTC
## Description
<pre>    Design System → Static Implementation → Dynamic Implementation
    vocabulary → prototype → final
    vocabulary → [project]-prototype → [project]-[implementation(s)] (*-dev-env *-theme, etc.)
</pre>
 <.pre> Tag in Structure and Behavior section is  causing horizontal scrollbar as it is not adjusting to the screen size because of its default behavior it maintains the style spaces and line breaks that are used in code . it also causes shrinking of other content

## Reproduction
go  to https://vocabulary-docs.netlify.app/  
open developer tools switch to responsive tab 
adjust window for smaller devices  you can see the horizontal scroll bar 

## Screenshots
![ss of non responsive documnetation](https://github.com/user-attachments/assets/ddf8c0e4-b990-4690-9837-b125cca15e2b)

## Environment
 - Device: (samsung galaxy s20,desktop )
 - OS: (_Android)
 - Browser: (Chrome)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by possumbilities** [comment] 2024-10-07 13:09
Hi @OmarAmeen01 I believe this is intended behavior for the code areas, as they are not set to line-wrap and therefore as the visible horizontal space shrinks the ability to scroll to view the code is necessary. 

Closing.

**Closed as not planned by possumbilities** 2024-10-07 13:09 UTC
Labels: 🟧 priority: high, ⛔️ status: discarded, 🛠 goal: fix, 💻 aspect: code
