### ISSUE TITLE
[Feature] Add table of content/side menu to docs page - use vocabulary

### ISSUE THREAD

**Issue by FatumaA** [creativecommons/vocabulary#96] opened 2024-10-05 00:44 UTC
## Problem
The docs page is long and has no internal navigation to help the user easily navigate it except for the three bullet points listed.

![Group 1 (2)](https://github.com/user-attachments/assets/352bf49a-bdf0-42eb-96b8-1b18b2049efd)

## Description
At the moment, the docs page has only three list items to navigate. They stay at the top of the file, making it hard to know where you are on the page. 

## Alternatives
My suggestion would be to uncomment the vocabulary import and use it to add the side navigation or some sort of sticky navigation, or to add it using the provided style.css file. 

This navigation is pretty standard in docs sites and will make a later transition easier.

## Implementation
- [x] I would be interested in implementing this feature.

**Comment by possumbilities** [comment] 2024-10-07 13:26
Hi and thanks for this contribution! This is a duplicate of 
- #61 

Please check that an Issue is not already open before opening a new one, and if so add additional context as comments to the existing Issue.

Please see the [Contribution Guidelines](https://opensource.creativecommons.org/contributing-code/) for more information.

**Closed as not planned by possumbilities** 2024-10-07 13:26 UTC
Labels: 🟩 priority: low, ⛔️ status: discarded, ✨ goal: improvement, 💻 aspect: code

**Comment by FatumaA** [comment] 2024-10-07 17:07
> Hi and thanks for this contribution! This is a duplicate of #61 Please check that and Issue is not already open before opening a new one, and if so add additional context as comments to the existing Issue.
> 
> Please see the [Contribution Guidelines](https://opensource.creativecommons.org/contributing-code/) for more information.

Apologies, I hadn't seen the older issue. I'm guessing my assignment here is a mistake as the other issue says this is blocked till further notice?
