### ISSUE TITLE
[Bug] Non-functional explore button and Inconsistency in explore-panel.

### ISSUE THREAD

**Issue by SumaiyaaRq** [creativecommons/vocabulary#192] opened 2024-10-14 07:38 UTC
## Description
The  **explore button** in **archive-page.html** file of context folder is not functional and the **explore-panel** in the **index-logo.html** file of context folder is not consistent .

## Reproduction

1. Go to the mentioned folder.
2.Run the archive-page.html file.
   i)Click on **Explore CC** button , it won't function
3. Run the index-logo.html file.
   i)Click on **Explore CC** button , check the explore-panel.

## Expectation
The explore button should be functional and the explore panel must maintain consistency according to the vocabulary documentation.

## Screenshots

index-logo.html page :
<img width="1440" alt="Screenshot 2024-10-14 at 12 37 23 PM" src="https://github.com/user-attachments/assets/d8373e8a-bace-455d-9139-8e5f9f417c84">

## Environment

 - Device: MacBook Air
 - OS: macOs 15.0.1
 - Browser: chrome
 - Other info: display resolution:2560×1664 pixels

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by possumbilities** [comment] 2024-10-14 14:26
Hi @SumaiyaaRq theses are two distinct Issues, please don't group items in this way. It is more helpful to keep Issues distinct and focused in scope so they can be addressed more clearly.

I am unable to reproduce the the first reported item in this Issue, visiting the live example version at current works as expected: https://vocabulary-docs.netlify.app/specimen/contexts/archive-page.html

Vocabulary accounts for two levels of use, at the main Index Project and for Ancilliary/downstream projects, each of these has a different approach to the explore panel contents as outlined in the comments. This is expected behavior. 

Closing for now, unable to reproduce and intended behavior.

**Comment by SumaiyaaRq** [comment] 2024-10-14 15:31
Hi @possumbilities , I would definitely raise issues distinctly the next time . As for the first item in the issue I want to share that whenever I am running the archive-page.html locally ,the explore button seems to be non-functional.

**Closed as not planned** 2024-10-14 16:33 UTC
Labels: 🟩 priority: low, ⛔️ status: discarded, 🛠 goal: fix, 💻 aspect: code
