### ISSUE TITLE
[Bug] links attached to anchor tags of few headings are leading back to the same page of blog-post

### ISSUE THREAD

**Issue by yashi-hub** [creativecommons/vocabulary#131] opened 2024-10-07 20:42 UTC
## Description
Several clickable, underlined words on the **blog-post** page are redirecting to the same URL as the blog-post page itself.
these underlined words include: [Open Culture] , [Amanda Conway], [Ólafur Jónsson], [Copyright and Artists], [Somos El Bien Común], [Apollo 11 Commander Neil Armstrong] and all the topics under the title: **Tags** 
Infact the headers also do not work except for "explore CC"- 
![image](https://github.com/user-attachments/assets/684d6367-4307-4b97-beda-cbe052ccd808)

## Reproduction
Option 1: Make these buttons non-clickable.

Option 2: Update the URL behind each button to redirect appropriately based on the intended heading.

## Expectation
The clickable words should properly redirected to the intended page or it should not be underlined and click should not be enabled on them
## Screenshots
![image](https://github.com/user-attachments/assets/4e905b1e-0e0b-44de-a934-ccc354a07a81)
here I am hovering on the "Open Culture" word and bottom left you can see the same hyperlink as of the blog-post page itself

## Environment
 - Device: (_eg. laptop)
 - Browser: (_eg._ Safari; Firefox)

**Comment by possumbilities** [comment] 2024-10-08 12:53
This is by intention, the Vocabulary specimens are scaffolding. They are meant as example use
cases for rendering, testing, and development. These are links that largely act as placeholders, therefore they use the convention of having their href set to `#` which makes them not go anywhere, just the same page. 

Closing, as this is intended behavior.

**Closed as not planned by possumbilities** 2024-10-08 12:53 UTC
Labels: 🟧 priority: high, 🟩 priority: low, ⛔️ status: discarded, 🛠 goal: fix, 💻 aspect: code
