### ISSUE TITLE
[Bug] Mobile responsiveness issue on program-index.html

### ISSUE THREAD

**Issue by Arinzelight** [creativecommons/vocabulary#110] opened 2024-10-06 15:50 UTC
## Description
The related posts section in program-index.html is not displaying properly on mobile devices. The layout is not responsive, causing elements to overflow.

## Reproduction
1. Open program-index.html on a mobile device or in a responsive design testing tool.
2. Scroll to the related posts section.
3. Observe that the elements are not responsive and the layout breaks.
4. See error.

## Expectation
The related posts section should adjust to different screen sizes, stacking elements vertically on smaller screens while maintaining a clean and user-friendly layout.

## Screenshots
![program-page](https://github.com/user-attachments/assets/8e3761cd-e3eb-4d25-b876-de9f0d0543f2)

## Environment

- Device: (e.g. iPhone 12, Samsung Galaxy S10)
- OS: (e.g. iOS 14.4, Android 11)
- Browser: (e.g. Safari, Chrome)
- Version: (e.g. iOS 14.4; Chrome 92)
- Other info: (e.g. screen resolution 375x812_)

## Additional context
The CSS for the related posts section may need adjustments to ensure proper flexbox/grid settings

## Resolution
- [x] I would be interested in resolving this bug.

**Comment by mannika763** [comment] 2024-10-06 17:19
Hey @Arinzelight,
Could you let me know the process for assigning this issue to me?

**Comment by Arinzelight** [comment] 2024-10-06 18:38
Hi @mannika763,
if the issue has been updated to ready for work, you can of course  go ahead and work on the task then create a pull request because more than one person can work on a task or approved issue

**Comment by possumbilities** [comment] 2024-10-07 18:22
Work for this would need to discern whether this is a style change, or whether this is actually a markup change, since this behavior doesn't occur on other contexts utilizing the same element.

This issue is specifically about the Recent Posts not changing layout at narrower breakpoints. This element seems to appear correctly on other pages so this might be a matter of altering HTML structure only.

I would suggest those that wish to investigate a solution here to first investigate the cause.

**Comment by iyinolawumi** [comment] 2024-10-07 21:17
Hi @possumbilities 
I was able to do a small thing on this issue by adjusting the grid. Kindly check and please give a feedback. Thank you

**Comment by OmarAmeen01** [comment] 2024-10-08 15:51
@possumbilities  in my PR  #82 `Made design system ui mobile responsive`   I fixed all these issues so you can close this issue and check that PR and provide me feedback on that . that PR deals with responsive in general in the design system and tries to fix these small issues on the way

**Comment by egbadon-victor** [comment] 2024-10-10 20:16
Hi @possumbilities .

Further investigation on this issue actually shows that it affects all occurences in other contexts. Hence, my approach would be a CSS targeted approach. Particularly targetting the grid style at lower screen sizes.

**Comment by OmarAmeen01** [comment] 2024-10-10 20:25
@egbadon-victor  if you found same on other pages too raise the issue wait for its approval my PR got  closed because it was covering fixes beyond mentioned in issue.

**Comment by egbadon-victor** [comment] 2024-10-10 20:38
@OmarAmeen01 yeah I understand. My PR for this issue will only cover the program-index page, even though it's a CSS targeted change

**Closed as completed** 2024-10-21 18:15 UTC
Labels: 🟨 priority: medium, 🏁 status: ready for work, 🛠 goal: fix, 💻 aspect: code
