### ISSUE TITLE
[Bug] Missing Image in some html pages.

### ISSUE THREAD

**Issue by SisiVero** [creativecommons/vocabulary#84] opened 2024-10-04 12:17 UTC
## Description
The image src throws and error that the image file does not exist, thereby causing a break in the interface.

## Expectation
It probably is a mistake as the source of the image (the image file- imgs) is missing

## Screenshots
Attached is a screengrab of the broken interface:

<img width="587" alt="DefaultPageImgError" src="https://github.com/user-attachments/assets/fe3855ef-cc55-4dff-8231-8afb1f863b55">

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by possumbilities** [comment] 2024-10-07 13:06
This is known and a largely a duplicate of #39. 

Closing for now as it overlaps.

**Closed as not planned by possumbilities** 2024-10-07 13:06 UTC
Labels: 🟧 priority: high, ⛔️ status: discarded, 🛠 goal: fix, 💻 aspect: code
