### ISSUE TITLE
[Bug] Missing Image Folder in Repo Causing Broken Images

### ISSUE THREAD

**Issue by mo-gbolahan** [creativecommons/vocabulary#109] opened 2024-10-06 10:27 UTC
## Description
The image folder is missing from the repository, which results in all images across the application being broken. This issue affects any component or page that relies on these images, leading to a poor user experience and visual inconsistencies throughout the app.

## Reproduction

1. Navigate to any page that is supposed to display images.
2. Observe that all images are broken, showing missing image placeholders.
3. Check the repo and confirm that the image folder is absent.

## Expectation
The repository should include an image folder containing all necessary image assets. Images should load correctly across all components and pages.

## Screenshots

![Screenshot (29)](https://github.com/user-attachments/assets/f464b50a-1ca4-40ca-af4d-19d3699effaf)

## Recommendation:

- Add the missing image folder and ensure it contains all necessary image assets.
- Verify that images are loading properly after the folder is restored.

## Environment

 - Device: (_eg._ iPhone Xs; laptop)
 - OS: (_eg._ iOS 13.5; Fedora 32)
 - Browser: (_eg._ Safari; Firefox)
 - Version: (_eg._ 13; 73)
 - Other info: (_eg._ display resolution, ease-of-access settings)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by mo-gbolahan** [comment] 2024-10-06 10:31
@TimidRobot 
I’d like to resolve the issue with the missing image folder, but I’m not sure what specific images you would prefer to use. Your guidance or any image assets you can provide would be really helpful in getting this fixed.

**Comment by possumbilities** [comment] 2024-10-07 13:33
Hi! This is a duplicate of #39 

Closing.

**Closed as not planned by possumbilities** 2024-10-07 13:33 UTC
Labels: 🟧 priority: high, ⛔️ status: discarded, 🛠 goal: fix, 💻 aspect: code
